site_name: Support de cours Informatique
site_url: https://eljyw.github.io/cours/
site_author: eljyw
repo_url: https://github.com/eljyw/cours
site_dir: public
theme:
  name: material
#  favicon: img/favicon.ico
#  logo: img/icon-32.png
  palette:
    primary: 'blue'
    accent: 'blue'
  feature:
    tabs: false
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - toc:
      toc_depth: 4
      permalink: True
  - codehilite
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list

nav:
  - Introduction: intro.md
  - Domaines:
    - langage C: langC.md
    - Unix: unix.md
#  - Other:
#    - GitLab CI template validation: gitlab-ci-template-validation.md

