site_name: Support de cours Informatique
site_url: http://gitlab-ci-templates.pages.forge.orange-labs.fr/doc
site_author: eljyw
repo_url: https://gitlab.forge.orange-labs.fr/gitlab-ci-templates
site_dir: public
theme:
  name: material
#  favicon: img/favicon.ico
#  logo: img/icon-32.png
  palette:
    primary: 'blue'
    accent: 'blue'
  feature:
    tabs: false
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - toc:
      toc_depth: 3
  - codehilite
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
nav:
  - Introduction: intro.md
  - Domaines:
    - langage C: langC.md
    - Unix: unix.md
#  - Other:
#    - GitLab CI template validation: gitlab-ci-template-validation.md
